In [1]:
!pip install pyspark

Collecting pyspark
  Downloading pyspark-3.2.0.tar.gz (281.3 MB)
     |████████████████████████████████| 281.3 MB 39 kB/s
Collecting py4j==0.10.9.2
  Downloading py4j-0.10.9.2-py2.py3-none-any.whl (198 kB)
     |████████████████████████████████| 198 kB 63.5 MB/s
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-3.2.0-py2.py3-none-any.whl size=281805912 sha256=41050bb0d71939a37c678551193a91a77c9491b12204b9fa211b9de183e6ae1b
  Stored in directory: /root/.cache/pip/wheels/0b/de/d2/9be5d59d7331c6c2a7c1b6d1a4f463ce107332b1ecd4e80718
Successfully built pyspark
Installing collected packages: py4j, pyspark
Successfully installed py4j-0.10.9.2 pyspark-3.2.0

In [2]:
from pyspark.sql import SparkSession
import pyspark.sql.functions as F
from pyspark.sql.types import StructType, StructField, StringType, IntegerType

In [3]:
spark = (
    SparkSession.builder
      .master('local')
      .appName('dataframe_withcolumn')
      .config('spark.ui.port', '4050')
      .getOrCreate()
)

In [6]:
#Informando um novo cabeçalho
df1 = (spark
       .read
       .format("csv")
       .option("header", "false") #Removeu o cabeçalho original
       .option("inferschema", "false")
       .option("delimiter", ";")
       .load('/content/drive/MyDrive/arquivo_geral.csv').toDF("UM", "DOIS", "TRES", "QUATRO", "CINCO", "SEIS", "SETE")
       #toDF = informou um novo cabeçalho
)

In [8]:
df1.show()
df1.printSchema()

+------+------+----------+----------+---------------+-----------+----------------+
|    UM|  DOIS|      TRES|    QUATRO|          CINCO|       SEIS|            SETE|
+------+------+----------+----------+---------------+-----------+----------------+
|regiao|estado|      data|casosNovos|casosAcumulados|obitosNovos|obitosAcumulados|
| Norte|    RO|2020-01-30|         0|              0|          0|               0|
| Norte|    RO|2020-01-31|         0|              0|          0|               0|
| Norte|    RO|2020-02-01|         0|              0|          0|               0|
| Norte|    RO|2020-02-02|         0|              0|          0|               0|
| Norte|    RO|2020-02-03|         0|              0|          0|               0|
| Norte|    RO|2020-02-04|         0|              0|          0|               0|
| Norte|    RO|2020-02-05|         0|              0|          0|               0|
| Norte|    RO|2020-02-06|         0|              0|          0|               0|
| Norte|    RO|2020-02-07|         0|              0|          0|               0|
| Norte|    RO|2020-02-08|         0|              0|          0|               0|
| Norte|    RO|2020-02-09|         0|              0|          0|               0|
| Norte|    RO|2020-02-10|         0|              0|          0|               0|
| Norte|    RO|2020-02-11|         0|              0|          0|               0|
| Norte|    RO|2020-02-12|         0|              0|          0|               0|
| Norte|    RO|2020-02-13|         0|              0|          0|               0|
| Norte|    RO|2020-02-14|         0|              0|          0|               0|
| Norte|    RO|2020-02-15|         0|              0|          0|               0|
| Norte|    RO|2020-02-16|         0|              0|          0|               0|
| Norte|    RO|2020-02-17|         0|              0|          0|               0|
+------+------+----------+----------+---------------+-----------+----------------+
only showing top 20 rows

root
 |-- UM: string (nullable = true)
 |-- DOIS: string (nullable = true)
 |-- TRES: string (nullable = true)
 |-- QUATRO: string (nullable = true)
 |-- CINCO: string (nullable = true)
 |-- SEIS: string (nullable = true)
 |-- SETE: string (nullable = true)

In [10]:
#Segunda forma de informar um novo cabeçalho
lista_esquema = ['UM', 'DOIS', 'TRES', 'QUATRO', 'CINCO', 'SEIS', 'SETE']
df1 = (spark
       .read
       .format("csv")
       .option("header", "false")
       .option("inferschema", "false")
       .option("delimiter", ";")
       .load('/content/drive/MyDrive/arquivo_geral.csv').toDF(*lista_esquema)
)
df1.show()

+------+------+----------+----------+---------------+-----------+----------------+
|    UM|  DOIS|      TRES|    QUATRO|          CINCO|       SEIS|            SETE|
+------+------+----------+----------+---------------+-----------+----------------+
|regiao|estado|      data|casosNovos|casosAcumulados|obitosNovos|obitosAcumulados|
| Norte|    RO|2020-01-30|         0|              0|          0|               0|
| Norte|    RO|2020-01-31|         0|              0|          0|               0|
| Norte|    RO|2020-02-01|         0|              0|          0|               0|
| Norte|    RO|2020-02-02|         0|              0|          0|               0|
| Norte|    RO|2020-02-03|         0|              0|          0|               0|
| Norte|    RO|2020-02-04|         0|              0|          0|               0|
| Norte|    RO|2020-02-05|         0|              0|          0|               0|
| Norte|    RO|2020-02-06|         0|              0|          0|               0|
| Norte|    RO|2020-02-07|         0|              0|          0|               0|
| Norte|    RO|2020-02-08|         0|              0|          0|               0|
| Norte|    RO|2020-02-09|         0|              0|          0|               0|
| Norte|    RO|2020-02-10|         0|              0|          0|               0|
| Norte|    RO|2020-02-11|         0|              0|          0|               0|
| Norte|    RO|2020-02-12|         0|              0|          0|               0|
| Norte|    RO|2020-02-13|         0|              0|          0|               0|
| Norte|    RO|2020-02-14|         0|              0|          0|               0|
| Norte|    RO|2020-02-15|         0|              0|          0|               0|
| Norte|    RO|2020-02-16|         0|              0|          0|               0|
| Norte|    RO|2020-02-17|         0|              0|          0|               0|
+------+------+----------+----------+---------------+-----------+----------------+
only showing top 20 rows

In [12]:
#Terceira maneira - Utilizando o Select com Fcol e Alias
df2 = (spark
       .read
       .format("csv")
       .option("header", "false")
       .option("inferschema", "false")
       .option("delimiter", ";")
       .load('/content/drive/MyDrive/arquivo_geral.csv')
)

df2 = df2.select(F.col("_c0").alias("um"),
                 F.col("_c1").alias("dois"),
                 F.col("_c2").alias("tres"),
                 F.col("_c3").alias("quatro"),
                 F.col("_c4").alias("cinco"),
                 F.col("_c5").alias("seis"),
                 F.col("_c6").alias("sete"),
)

df2.printSchema()

root
 |-- um: string (nullable = true)
 |-- dois: string (nullable = true)
 |-- tres: string (nullable = true)
 |-- quatro: string (nullable = true)
 |-- cinco: string (nullable = true)
 |-- seis: string (nullable = true)
 |-- sete: string (nullable = true)