Importando o pandas e apelidando como "pd"

In [3]:
import pandas as pd
#Ctrl + F9 para atualizar cada bloco de código

Importando a base de dados (dataframe) como "df", e a arazenando-a em uma variável

* read_csv - Lê o dataframe especificado. É necessário especificar o tipo de documento que será lido (csv, json, etc)

* sep = ";" - Em alguns arquivos csv, é necessário especificar o tipo de separador (vírgula ou ponto e vírgula)

* parse_dates=[""] - Converte um tipo de dado qualquer no tipo "Date"

In [4]:
df = pd.read_csv("/content/drive/MyDrive/ocorrencia.csv", sep=";", parse_dates=["ocorrencia_dia", "divulgacao_dia_publicacao"], dayfirst=True)

Imprimindo o dataframe

* Um dataframe não é uma tabela, é uma tabulação de dados.

In [ ]:
#print(df) #Retorna um resultado bagunçado
df #Retorna uma tabulação do arquivo csv, feita pelo pandas.

Para mostrar certa quantidade de linhas

In [ ]:
df.head(2) #Exibe duas linhas em ordem ascendente

In [ ]:
df.tail(2) #Exibe duas linhas em ordem decrescente

Para saber o tipo de dados

* Object: Se uma coluna possui um tipo diferente de dados, ela é tratada como um objeto.

* Quando uma coluna possui dados incoerêntes, não se pode fazer consultas.

In [ ]:
df.dtypes

Verificando a validade da data (após o parse)

In [ ]:
df.ocorrencia_dia.dt.month #Verificando quais são os valores de mês, se correspondem a sua posição no dataframe

Para pegar uma determinada célula dentro do dataframe (localização eixo X e eixo Y)

* X é equivalente ao rótulo, e Y é equivalente à coluna
* O eixo X é sempre obrigatório

In [ ]:
#df.loc[5000, "ocorrencia_dia"]
#df.loc[[2000]] #Para retornar apenas uma determinada linha
#df.loc[:, ["ocorrencia_dia"]] #Para retornar apenas uma determinada coluna
#df.loc[[10, 100, 1000]] #Para retornar apenas certas linhas #Para retorar mais de um valor, deve-se passa-los como lista
df.loc[[10, 100, 1000],["codigo_ocorrencia", "ocorrencia_dia"]] #Para retornar determinadas células, de determinadas linhas
#df.loc[::-1] #Inverte a ordem dos rótulos

      codigo_ocorrencia ocorrencia_dia
10                39789     2010-01-10
100               40170     2010-03-20
1000              45064     2011-10-01

Para saber se uma coluna possui valores repetidos

* True significa que a coluna não possui valores repetidos
* False significa que a coluna possui valores repetidos

In [ ]:
df.codigo_ocorrencia.is_unique #cf.nome_coluna.is_unique

True

Para alterar o rótulo automático do dataframe usando uma coluna como índice

* É importante que a coluna usada como índice não possua valores repetidos

In [ ]:
df.set_index("codigo_ocorrencia", inplace=True)

In [ ]:
df

Para resetar as alterações feitas no índice

* inplace=True - Faz com que as alterações sejam aplicadas

In [ ]:
df.reset_index(drop=True, inplace=True)
df

Fazendo o backup de  uma coluna, antes de modificá-la

In [ ]:
df["coluna_backup"] = df.ocorrencia_aerodromo 
#Cria-se um array que armazena o valor da coluna original. 
#Este array será um bloco de dataframe, que será agregado ao dataframe.
df

Para excluir colunas

* Ao se tentar dropar uma coluna, é preciso alterar o eixo que o programa irá verificar. Por padrão, ele sempre verifica, obrigatóriamente, o eixo apenas o eixo X.

* axis=1 - ! corresponde ao eixo Y (coluna), e 0 corresponde ao eixo X (linhas)

In [ ]:
#df.drop(["coluna_backup"], axis=1, inplace=True) 
#Dependendo de como se usar o comando drop, ele pode excluir linhas ao invés de colunas

df

Para alterar o valor de uma célula específica

In [ ]:
df.loc[0, "ocorrencia_aerodromo"] = "LOSED"

df

Para alterar o valor de várias células em uma coluna

* Sintaxe - df.loc[df.nome_coluna1 == "valor", ["nome_coluna2"]] = novo_valor
  * Caso queira-se atribuir valores à uma coluna diferente da analisada, deve-se inserir o nome da coluna diferente no campo "nome_coluna2".

  * Caso queira-se atribuir valores á mesma coluna analisada, vece_se inserir o nome_coluna1 no campo "nome_coluna2"


Para verificar se o valor realmente foi alterado

* Sintaxe - df.loc[df.nome_coluna == "novo_valor"]

In [ ]:
df.loc[df.divulgacao_relatorio_numero == "***", ["divulgacao_relatorio_numero"]] = "NULL"
df

Para substinuir campos com certo valor por um outro valor

* Replace é mais comumente utilizado para substituir dados incoerêntes, classificando-os como vazios.
* pd.NA - Biblioteca do pandas que insere valores nulos no campo

In [ ]:
df.replace(["****", "***", "####", "NULL"], pd.NA, inplace=True)
df.head(10)

Para localiza todos os valores vazios

In [ ]:
#df.isna() #Retorna uma tabulação de todos os campos com "True" ou "False", dependendo se estão vazios ou não
df.isna().sum() #Para somar todos os valores vazios em cada coluna

Renomear colunas

In [ ]:
df.rename(columns={"codigo_ocorrencia1": "cod_ocorrencia1", "codigo_ocorrencia2": "cod_ocorrencia2"}, inplace=True)
df.head(10)